name: Azure SQL Query Runner
on: [workflow_dispatch]

env:
  SQL_SERVER: emi-qa-passportai-we-svm.database.windows.net
  DATABASE_NAME: GenAIStatistics
  SQL_QUERY: "SELECT TOP 10 * FROM dbo.MarketSize"

jobs:
  query-database:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Run Query with Python
      run: |
        sudo apt-get install -y python3-pip
        pip install pyodbc pandas

        TOKEN=$(az account get-access-token --resource https://database.windows.net --query accessToken -o tsv)

        python3 -c "
        import pyodbc, os, pandas as pd
        conn = pyodbc.connect(
        driver='{ODBC Driver 18 for SQL Server}',
        server=os.environ['SQL_SERVER'],
        database=os.environ['DATABASE_NAME'],
        Authentication='ActiveDirectoryPasswordless',
        AccessToken='$TOKEN'
        )
        df = pd.read_sql(os.environ['SQL_QUERY'], conn)
        df.to_csv('results.csv', index=False)
        print(df.to_markdown())
        "

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: sql-results
        path: results.csv
