name: Azure SQL Query
on: [workflow_dispatch]

permissions:
  id-token: write  # Required for OIDC
  contents: read   # For checking out code

env:
  SQL_SERVER: emi-qa-passportai-we-svm.database.windows.net
  DATABASE_NAME: GenAIStatistics
  SQL_QUERY: "SELECT TOP 10 * FROM dbo.MarketSize"  # Your query here

jobs:
  query-database:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: 635d8b8a-9ac3-47e8-82ce-4867e37a8918
        tenant-id: 251c4782-827b-4033-b7b5-12500263871f
        subscription-id: 20ad1290-7497-4769-8dab-674852082c0c

    - name: Install SQL Tools
      run: |
        # Install SQL command line tools
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update
        sudo apt-get install -y mssql-tools unixodbc-dev
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> $GITHUB_ENV

    - name: Execute SQL Query
      run: |
        # Get Azure AD access token for SQL Database
        TOKEN=$(az account get-access-token --resource https://database.windows.net --query accessToken -o tsv)
        
        # Run query and format output
        echo "Executing query: $SQL_QUERY"
        echo "--------------------------"
        sqlcmd -S "$SQL_SERVER" -d "$DATABASE_NAME" -G -P "$TOKEN" -Q "$SQL_QUERY" -s "|" -W -h-1
        echo "--------------------------"
        echo "Query completed successfully"
      
    - name: Save query results
      if: always()  # Runs even if previous step fails
      run: |
        TOKEN=$(az account get-access-token --resource https://database.windows.net --query accessToken -o tsv)
        sqlcmd -S "$SQL_SERVER" -d "$DATABASE_NAME" -G -P "$TOKEN" -Q "$SQL_QUERY" -o results.csv -y 0 -s ","
        
        # For multi-line results, use this instead:
        # sqlcmd -S "$SQL_SERVER" -d "$DATABASE_NAME" -G -P "$TOKEN" -Q "$SQL_QUERY" -o results.txt
        
      shell: bash

    - name: Upload results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: sql-query-results
        path: |
          results.csv
          # or results.txt if using the multi-line format
