name: Azure SQL Query Runner
on: [workflow_dispatch]

env:
  SQL_SERVER: emi-qa-passportai-we-svm.database.windows.net
  DATABASE_NAME: GenAIStatistics
  SQL_QUERY: "SELECT TOP 10 * FROM dbo.MarketSize"

jobs:
  query-database:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get Azure AD Token
      id: get-token
      run: |
        ACCESS_TOKEN=$(az account get-access-token --resource https://database.windows.net --query accessToken --output tsv)
        echo "Access Token (Base64 Encoded):"
        echo $ACCESS_TOKEN | base64  # Encode to bypass GitHub masking

    - name: Run SQL Query via Docker
      run: |
        token=$(az account get-access-token --resource https://database.windows.net --query accessToken -o tsv)
        az sql query -S emi-qa-passportai-we-svm.database.windows.net -d GenAIStatistics --access-token "$token" -Q "SELECT TOP 10 * FROM dbo.MarketSize"

        # Display results
        echo "Query Results:"
        cat results.csv

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: sql-results
        path: results.csv
